WIP dynamic UI themes
GeekGene/MewsFeed pull request #60
Opened 2023-03-01 22:33 UTC by mattyg

**Overview**
- add ui dep pinia-persistedstate-plugin
- architecture for selecting & applying a theme dynamically
- 3 example themes: Light, Dark & Cat

2023-03-17 03:24 UTC, jost-s commented
Cool feature!

The dark mode is too dark in some places IMO, for example when editing the profile
<img width="433" alt="image" src="https://user-images.githubusercontent.com/28270981/225804215-0855490a-6c43-4dce-9daf-d2a8db548871.png">


Or when looking at an agent profile
<img width="753" alt="image" src="https://user-images.githubusercontent.com/28270981/225804272-d97c0877-7dc4-4223-a72b-9dc3e5ecff4e.png">

The "Reply" heading is faint too
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/28270981/225804990-4e79217b-a876-446a-9ac9-e3fbb43eb031.png">


The cat theme - well =D, cat image aside, readability suffers as well:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/28270981/225804622-57c92db8-3563-4583-857f-dea2fe52530a.png">

2023-03-17 03:27 UTC, jost-s requested changes
Only cosmetic changes requested

2023-03-17 03:27 UTC, jost-s commented on ui/src/components/MewList.vue
> +  console.log('going!');
```suggestion
```

2023-04-04 21:07 UTC, mattyg commented
Since we're leaning towards #65 which will superseed this ticket, and it feels lower priority for now. I'm going to close this PR.

2023-04-04 21:07 UTC, closed without merging